version: 2
jobs:
   java_8_test_current:
     docker:
       - image: circleci/openjdk:8u141
     steps:
        - checkout
        - run:
            name: Java 8 - Test current version
            command: ./mvnw -Pdistribute,snapshot,docs,convergence clean test

   java_8_test_spring_next:
     docker:
       - image: circleci/openjdk:8u141
     steps:
        - checkout
        - run:
            name: Java 8 - Test Spring.NEXT
            command: ./mvnw -Pspringnext,convergence clean test

   java_8_test_spring_buildsnapshot:
     docker:
       - image: circleci/openjdk:8u141
     steps:
        - checkout
        - run:
            name: Java 8 - Test Spring.NEXT
            command: ./mvnw -Pspring-buildsnapshot,convergence clean test

   java_11_test_current:
     docker:
       - image: circleci/openjdk:11-ea-27-jdk-sid
     steps:
        - checkout
        - run:
            name: Java 11 - Test current version
            command: ./mvnw -Pdistribute,snapshot,docs,java11,convergence clean test

   java_11_test_spring_next:
     docker:
       - image: circleci/openjdk:11-ea-27-jdk-sid
     steps:
        - checkout
        - run:
            name: Java 11 - Test Spring.NEXT
            command: ./mvnw -Pspringnext,java11,convergence clean test

   java_11_test_spring_buildsnapshot:
     docker:
       - image: circleci/openjdk:11-ea-27-jdk-sid
     steps:
        - checkout
        - run:
            name: Java 11 - Test Spring.NEXT
            command: ./mvnw -Pspring-buildsnapshot,java11,convergence clean test

   deploy:
     docker:
       - image: circleci/openjdk:8u141
     steps:
        - checkout
        - run:
            name: Deploy to Artifactory
            command: ./deploy.bash
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - java_8_test_current
      - java_11_test_current
      - java_8_test_spring_next
      - java_11_test_spring_next
      - java_8_test_spring_buildsnapshot
      - java_11_test_spring_buildsnapshot
      - deploy:
          requires:
            - java_8_test_current
            - java_11_test_current
            - java_8_test_spring_next
            - java_11_test_spring_next
            - java_8_test_spring_buildsnapshot
            - java_11_test_spring_buildsnapshot

general:
  branches:
    ignore:
      - gh-pages # list of branches to ignore

dependencies:
  cache_directories:
    - "~/.m2"
